Parameters:
  AcmCertificateArn:
    Type: String
    Description: ACM Certificate for registerd domain name
  AppDomainName:
    Type: String
    Description: The app domain name - manual SSL in N.Virginia region

Resources:
  WebBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private

  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Sid: PublicReadForGetBucketObjects
          Principal:
            AWS:
              - !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudfrontIdentity}"
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebBucket', /*]]

  CloudfrontPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "CloudfrontPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - !Join ['', ['arn:aws:s3:::', !Ref 'WebBucket', /*]]

  CloudfrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Used to access S3 Web bucket"

  CloudfrontDistribution:
    DependsOn: [WebBucket]
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebBucket.DomainName
            Id: !Ref WebBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudfrontIdentity}"
        Aliases:
        - !Sub "*.${AppDomainName}"
        - !Sub "${AppDomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: false
          MaxTTL: 86400
          MinTTL: 0
          TargetOriginId: !Ref WebBucket
          ViewerProtocolPolicy : "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: true
        Comment: React Front End
        HttpVersion: "http2"
        IPV6Enabled: false
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"