name: CFDN Deploy
run-name: ${{ github.actor }} merge main
on:
  push:
    branches: [main]
env:
  AWS_ECR_ROLE: ${{ vars.AWS_ECR_ROLE }}
permissions:
  id-token: write
  contents: read
jobs:
  Merge-Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        - run: npm ci
        - run: npm run lint
        - run: npm run test:ci
        - run: npm run build
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: ${{ env.AWS_ECR_ROLE }}
      #     role-session-name: ECRPushSession
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ env.AWS_ECR_REGISTRY }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $REGISTRY:$IMAGE_TAG .
      #     docker push $REGISTRY:$IMAGE_TAG