name: CFDN Deploy
run-name: ${{ github.actor }} merge main
on:
  push:
    branches: [main]
env:
  AWS_ROLE: ${{ vars.AWS_ROLE }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
permissions:
  id-token: write
  contents: read
jobs:
  Merge-Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy files to the s3 website content bucket
        run:
          aws s3 sync --delete dist/ s3://${{ env.AWS_S3_BUCKET }}
          aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'

      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ env.AWS_ECR_REGISTRY }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $REGISTRY:$IMAGE_TAG .
      #     docker push $REGISTRY:$IMAGE_TAG